name: 'agile:base'
favicon: null
layout_spectrum: 0.50439
typography_spectrum: 0.32941
title: 'agile:base - business agility through technology'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1eb79c'
    - '#5a3664'
    - '#f7ac42'
    - '#000000'
    - '#00ffff'
  brandStrength: 0.875
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
