name: 'agile:base'
favicon: null
layout_spectrum: 0.48127
typography_spectrum: 0.32941
title: 'agile:base - business agility through technology'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6ac9d5'
    - '#9175b1'
    - '#953582'
    - '#f59d00'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
