name: 'agile:base'
favicon: null
layout_spectrum: 0.6440023968461901
typography_spectrum: 0.29226
title: 'agile:base - business agility through technology'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#96c45b'
    - '#aa3555'
    - '#3e97ac'
    - '#040604'
  brandStrength: 0.625
  lightness: 0.4175568127539009
  saturation: 0.17427622457034886
  rhythmicContrast: 0.5636568139307201
purpose: []
